In [1]:
import cv2
import datetime
import numpy as np


In [2]:
# Read all the PNG pics into a dict named Images key: Date(20210101) Value: RGB of the pic of that day
start = datetime.datetime.fromisoformat('2020-12-31')
delta = datetime.timedelta(days=1)
end = start + datetime.timedelta(days=365)
endnow=str(end.strftime('%Y%m%d'))
offset=start
# store the date
keys= []
# store the image date
Images = {}
while str(offset.strftime('%Y%m%d')) != endnow:
    offset += delta
    date = str(offset.strftime('%Y%m%d'))
    keys.append(date)
    path = './Png/' + date + '.png'
    Images[date] = cv2.imread(path)


In [3]:
# Use the keys list to iterate the date
Mark_data = []
lower_green = np.array([40,80,40])
upper_green = np.array([90,255,255])
for i in range(0,365):
    key = keys[i]
    image = Images[key]
    if image is None:
        for a in range(0,24):
            Mark_data.append(0)
        continue
    else:
        for hour in range(0,5760,240):
            img = image[:,hour:hour+240]
            hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
            #set the lower and upper bounds for the green hue

            #create a mask for green colour using inRange functio
            Mask = cv2.inRange(hsv,lower_green,upper_green)
            white = 0
            x,y = Mask.shape
            for i in range(x):
                for j in range(y):
                    if Mask[i][j] != 0:
                        white+=1
            rate = white/(x*y)
            if rate > 0.05:
                Mark_data.append(1)
            else:
                Mark_data.append(0)



        


In [ ]:
import json
import os
with open('Aurora.json', 'w') as  f:
    json.dump(Mark_data, f)

In [8]:
img = Images['20211017'][:,2401:2641]
test = img
hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
#set the lower and upper bounds for the green hue
lower_green = np.array([40,80,40])
upper_green = np.array([90,255,255])
#create a mask for green colour using inRange functio
Mask = cv2.inRange(hsv,lower_green,upper_green)
#perform bitwise and on the original image arrays using the mask
res= cv2.bitwise_and(img,img,mask = Mask)
cv2.namedWindow("mask",cv2.WINDOW_NORMAL)
#display the images
black = 0
white = 0
x,y = Mask.shape
for i in range(x):
    for j in range(y):
        if Mask[i][j] != 0:
            white+=1
rate1 = white/(x*y)
# round()第二个值为保留几位有效小数。
print("白色占比:", round(rate1*100,2),'%')
print(Mask)
cv2.imshow("mask",Mask)
cv2.imshow('image', test)
cv2.waitKey(0)
cv2.destroyAllWindows()
 

白色占比: 9.36 %
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]


In [10]:
test = Images['20211130'][:,2401:2641]

In [54]:
test

array([[[ 73, 107,  59],
        [ 73, 107,  59],
        [ 73, 107,  59],
        ...,
        [ 59, 107,  52],
        [ 59, 107,  52],
        [ 89, 134,  75]],

       [[ 59, 107,  52],
        [ 59, 107,  52],
        [ 89, 134,  75],
        ...,
        [ 59, 107,  52],
        [ 79, 142,  79],
        [ 59, 107,  52]],

       [[ 59, 107,  52],
        [ 59, 107,  52],
        [ 73, 107,  59],
        ...,
        [ 79, 142,  79],
        [ 59, 107,  52],
        [ 59, 107,  52]],

       ...,

       [[ 53,  79,  54],
        [ 70,  85,  60],
        [ 53,  79,  54],
        ...,
        [ 53,  79,  54],
        [ 70,  85,  60],
        [ 53,  79,  54]],

       [[ 70,  85,  60],
        [ 70,  85,  60],
        [ 70,  85,  60],
        ...,
        [ 67,  74,  56],
        [ 67,  74,  56],
        [ 70,  85,  60]],

       [[ 70,  85,  60],
        [ 50,  84,  77],
        [ 70,  85,  60],
        ...,
        [ 53,  79,  54],
        [ 53,  79,  54],
        [ 53,  79,  54]]

In [11]:
cv2.imshow('image', test)
cv2.waitKey(0)
cv2.destroyAllWindows()